# Generated by Django 4.1.7 on 2023-04-04 12:00

from django.db import migrations, models
import django.db.models.deletion
import pages.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='Processing', max_length=25)),
                ('num_links', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', pages.fields.TruncatedCharField(max_length=75)),
                ('url', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pagemodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
