version: '3.7'

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/run-backend.sh
    expose:
      - 5000
    network_mode: "host"
    volumes:
      - database:/app

  celery:
    image: webscrapper_backend:latest
    entrypoint: /app/run-celery.sh
    network_mode: "host"
    volumes:
      - database:/app

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    command: "npm run dev"
    expose:
      - 3000
    network_mode: "host"

volumes:
  database: {}
